name: Run tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install npm modules
        run: npm install

      - name: Run unit tests
        run: npm test
